###
GET http://localhost:3333/api/proyectos
access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiY2Fyb2wiLCJjcmVhdGVBdCI6MTU5MjE2MTc1NCwiZXhwaXJlQXQiOjE1OTI3NjY1NTR9.VHG3CWmOrX_ziGRKIlcCNCo6-uqrgEz84A_-pJYlz1w

### 
GET http://localhost:3333/api/proyectos/5ee675f9b5efac5e721c192b
access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiY2Fyb2wiLCJjcmVhdGVBdCI6MTU5MjE2MTc1NCwiZXhwaXJlQXQiOjE1OTI3NjY1NTR9.VHG3CWmOrX_ziGRKIlcCNCo6-uqrgEz84A_-pJYlz1w

###
GET http://localhost:3333/api/proyectos/categoria/frontend
access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiY2Fyb2wiLCJjcmVhdGVBdCI6MTU5MjE2MTc1NCwiZXhwaXJlQXQiOjE1OTI3NjY1NTR9.VHG3CWmOrX_ziGRKIlcCNCo6-uqrgEz84A_-pJYlz1w

###
POST http://localhost:3333/api/proyectos
Content-Type: application/json
access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiY2Fyb2wiLCJjcmVhdGVBdCI6MTU5MjE2MTc1NCwiZXhwaXJlQXQiOjE1OTI3NjY1NTR9.VHG3CWmOrX_ziGRKIlcCNCo6-uqrgEz84A_-pJYlz1w

{
  "titulo": "Curriculum web carol",
  "descripcion": "Mi portafolio :)",
  "url": "http://www.google.es",
  "cliente": "Google",
  "urlCliente": "http://www.google.es/quien-somos",
  "categoria": "nodejs"
}

###
PUT http://localhost:3333/api/proyectos/5ec172d2e9e09e0951267c88
Content-Type: application/json
access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiY2Fyb2wiLCJjcmVhdGVBdCI6MTU5MjE1OTY1MiwiZXhwaXJlQXQiOjE1OTI3NjQ0NTJ9.C810PcTgC0dhgAD4rrFRlp0vTCqzjCNoyyrEODyPzcA

{
  "titulo": "Proyecto EDITADO V2",
  "descripcion": "Esta es la descripción",
  "url": "http://www.google.es",
  "cliente": "Google",
  "urlCliente": "http://www.google.es/quien-somos",
  "categoria": "frontend"
}

###
DELETE http://localhost:3333/api/proyectos/5ec1709ecfbbf808afef4ea5

###
GET http://localhost:3333/api/token

### PRODUCCIÓN
GET https://cv-back-carol.herokuapp.com/api/proyectos
access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiY2Fyb2wiLCJjcmVhdGVBdCI6MTU5MTk5MjE2MywiZXhwaXJlQXQiOjE1OTE5OTI0NjN9.XsFvscEE0_QIt2HMMjkwkuLbYeFD5C18RyhBRNtwmkQ

###
GET https://cv-back-carol.herokuapp.com/api/token
